In [2]:
import pandas as pd
import numpy as np

In [3]:
dict1 = {
    "name" : ["a","b","c","d"],
    "city" : ["delhi","gurugram","chennai","mumbai"],
    "marks" : [38, 83, 59, 79]
}

In [4]:
df = pd.DataFrame(dict1)

In [5]:
df

  name      city  marks
0    a     delhi     38
1    b  gurugram     83
2    c   chennai     59
3    d    mumbai     79

In [6]:
df.to_csv("friends.csv")

In [7]:
df.to_csv("friends_index_false.csv", index=False)

In [8]:
df.head(2)

  name      city  marks
0    a     delhi     38
1    b  gurugram     83

In [9]:
df.tail(2)

  name     city  marks
2    c  chennai     59
3    d   mumbai     79

In [10]:
df.describe()

           marks
count   4.000000
mean   64.750000
std    20.694202
min    38.000000
25%    53.750000
50%    69.000000
75%    80.000000
max    83.000000

In [11]:
train = pd.read_csv("sample.csv")

In [12]:
train

   Train No      City  Speed
0     13802     delhi     92
1     38312  gurugram    138
2     32423   chennai    128
3     34913    mumbai     80

In [13]:
train['City'][0]

'delhi'

In [14]:
train["Speed"][1] = 120

C:\Users\saram\AppData\Local\Temp\ipykernel_26840\564732497.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  train["Speed"][1] = 120
C:\Users\saram\AppData\Local\Temp\ipykernel_26840\564732497.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train["Speed"][1] = 120

In [15]:
train

   Train No      City  Speed
0     13802     delhi     92
1     38312  gurugram    120
2     32423   chennai    128
3     34913    mumbai     80

In [16]:
train.index = ["first", "second", "third", "fourth"]

In [17]:
train

        Train No      City  Speed
first      13802     delhi     92
second     38312  gurugram    120
third      32423   chennai    128
fourth     34913    mumbai     80

In [18]:
ser = pd.Series(np.random.rand(34))

In [19]:
ser

0     0.253800
1     0.815038
2     0.886425
3     0.076377
4     0.873501
5     0.215556
6     0.999714
7     0.673668
8     0.204622
9     0.498929
10    0.196922
11    0.848969
12    0.654704
13    0.317727
14    0.802673
15    0.130502
16    0.634326
17    0.849539
18    0.495422
19    0.168092
20    0.422638
21    0.556240
22    0.014797
23    0.461004
24    0.000210
25    0.436208
26    0.877387
27    0.011220
28    0.214787
29    0.877570
30    0.666079
31    0.884200
32    0.021790
33    0.405658
dtype: float64

In [20]:
type(ser)

pandas.core.series.Series

In [21]:
newdf = pd.DataFrame(np.random.rand(334,5), index=np.arange(334))

In [22]:
newdf

            0         1         2         3         4
0    0.707436  0.654081  0.608428  0.631050  0.094173
1    0.086955  0.957513  0.235887  0.648301  0.513132
2    0.680814  0.912251  0.466365  0.297539  0.369094
3    0.859121  0.042389  0.500005  0.561147  0.303200
4    0.991908  0.331656  0.591858  0.856721  0.367924
..        ...       ...       ...       ...       ...
329  0.794219  0.487633  0.035823  0.773380  0.462670
330  0.934680  0.332451  0.875441  0.258823  0.068125
331  0.148264  0.855316  0.596798  0.417520  0.621319
332  0.895031  0.119942  0.625321  0.005616  0.839709
333  0.949934  0.051184  0.692991  0.324124  0.236691

[334 rows x 5 columns]

In [23]:
type(newdf)

pandas.core.frame.DataFrame

In [24]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [25]:
train.dtypes

Train No     int64
City        object
Speed        int64
dtype: object

In [26]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.498195    0.486781    0.497956    0.489782    0.485833
std      0.300409    0.291746    0.287295    0.280227    0.292928
min      0.002179    0.000797    0.000780    0.000454    0.008049
25%      0.234665    0.234443    0.243848    0.252053    0.234208
50%      0.525069    0.474906    0.497611    0.472952    0.461199
75%      0.767974    0.709441    0.753654    0.727418    0.754866
max      0.999209    0.998083    0.979170    0.999316    0.997284

In [27]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int32', length=334)

In [28]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [29]:
train.columns

Index(['Train No', 'City', 'Speed'], dtype='object')

In [30]:
newdf.to_numpy()

array([[0.70743591, 0.65408142, 0.60842802, 0.63104999, 0.09417283],
       [0.08695525, 0.95751259, 0.23588687, 0.64830079, 0.51313223],
       [0.68081406, 0.91225101, 0.46636524, 0.29753948, 0.3690938 ],
       ...,
       [0.14826418, 0.85531619, 0.59679776, 0.41752022, 0.62131864],
       [0.89503108, 0.1199417 , 0.62532058, 0.00561649, 0.83970946],
       [0.94993388, 0.05118381, 0.69299079, 0.32412381, 0.23669098]])

In [31]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.707436,0.086955,0.680814,0.859121,0.991908,0.202707,0.941428,0.661165,0.369502,0.624044,...,0.875448,0.639552,0.669815,0.547621,0.048537,0.794219,0.934680,0.148264,0.895031,0.949934
1,0.654081,0.957513,0.912251,0.042389,0.331656,0.648679,0.092945,0.807727,0.330430,0.096907,...,0.857178,0.203918,0.450909,0.797411,0.997914,0.487633,0.332451,0.855316,0.119942,0.051184
2,0.608428,0.235887,0.466365,0.500005,0.591858,0.636242,0.754851,0.308768,0.978849,0.609195,...,0.582506,0.093882,0.584969,0.840309,0.090226,0.035823,0.875441,0.596798,0.625321,0.692991
3,0.631050,0.648301,0.297539,0.561147,0.856721,0.254027,0.698789,0.312050,0.365258,0.361738,...,0.742572,0.829839,0.104720,0.339774,0.238517,0.773380,0.258823,0.417520,0.005616,0.324124
4,0.094173,0.513132,0.369094,0.303200,0.367924,0.300921,0.662259,0.360896,0.133999,0.212155,...,0.956559,0.277507,0.056233,0.336627,0.949106,0.462670,0.068125,0.621319,0.839709,0.236691

In [32]:
newdf.sort_index(axis=0, ascending= False)

            0         1         2         3         4
333  0.949934  0.051184  0.692991  0.324124  0.236691
332  0.895031  0.119942  0.625321  0.005616  0.839709
331  0.148264  0.855316  0.596798  0.417520  0.621319
330  0.934680  0.332451  0.875441  0.258823  0.068125
329  0.794219  0.487633  0.035823  0.773380  0.462670
..        ...       ...       ...       ...       ...
4    0.991908  0.331656  0.591858  0.856721  0.367924
3    0.859121  0.042389  0.500005  0.561147  0.303200
2    0.680814  0.912251  0.466365  0.297539  0.369094
1    0.086955  0.957513  0.235887  0.648301  0.513132
0    0.707436  0.654081  0.608428  0.631050  0.094173

[334 rows x 5 columns]

In [33]:
type(newdf[0])

pandas.core.series.Series

In [34]:
newdf2 = newdf

In [35]:
newdf2[0][0] = 0.3829

C:\Users\saram\AppData\Local\Temp\ipykernel_26840\449023582.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0] = 0.3829

In [36]:
newdf

            0         1         2         3         4
0    0.382900  0.654081  0.608428  0.631050  0.094173
1    0.086955  0.957513  0.235887  0.648301  0.513132
2    0.680814  0.912251  0.466365  0.297539  0.369094
3    0.859121  0.042389  0.500005  0.561147  0.303200
4    0.991908  0.331656  0.591858  0.856721  0.367924
..        ...       ...       ...       ...       ...
329  0.794219  0.487633  0.035823  0.773380  0.462670
330  0.934680  0.332451  0.875441  0.258823  0.068125
331  0.148264  0.855316  0.596798  0.417520  0.621319
332  0.895031  0.119942  0.625321  0.005616  0.839709
333  0.949934  0.051184  0.692991  0.324124  0.236691

[334 rows x 5 columns]

In [37]:
newdf3 = newdf.copy()

In [39]:
newdf3[0][0] = 1

C:\Users\saram\AppData\Local\Temp\ipykernel_26840\473980077.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf3[0][0] = 1

In [40]:
newdf3

            0         1         2         3         4
0    1.000000  0.654081  0.608428  0.631050  0.094173
1    0.086955  0.957513  0.235887  0.648301  0.513132
2    0.680814  0.912251  0.466365  0.297539  0.369094
3    0.859121  0.042389  0.500005  0.561147  0.303200
4    0.991908  0.331656  0.591858  0.856721  0.367924
..        ...       ...       ...       ...       ...
329  0.794219  0.487633  0.035823  0.773380  0.462670
330  0.934680  0.332451  0.875441  0.258823  0.068125
331  0.148264  0.855316  0.596798  0.417520  0.621319
332  0.895031  0.119942  0.625321  0.005616  0.839709
333  0.949934  0.051184  0.692991  0.324124  0.236691

[334 rows x 5 columns]

In [41]:
newdf

            0         1         2         3         4
0    0.382900  0.654081  0.608428  0.631050  0.094173
1    0.086955  0.957513  0.235887  0.648301  0.513132
2    0.680814  0.912251  0.466365  0.297539  0.369094
3    0.859121  0.042389  0.500005  0.561147  0.303200
4    0.991908  0.331656  0.591858  0.856721  0.367924
..        ...       ...       ...       ...       ...
329  0.794219  0.487633  0.035823  0.773380  0.462670
330  0.934680  0.332451  0.875441  0.258823  0.068125
331  0.148264  0.855316  0.596798  0.417520  0.621319
332  0.895031  0.119942  0.625321  0.005616  0.839709
333  0.949934  0.051184  0.692991  0.324124  0.236691

[334 rows x 5 columns]

In [42]:
newdf.loc[0,0] = 0.2

In [43]:
newdf.head()

          0         1         2         3         4
0  0.200000  0.654081  0.608428  0.631050  0.094173
1  0.086955  0.957513  0.235887  0.648301  0.513132
2  0.680814  0.912251  0.466365  0.297539  0.369094
3  0.859121  0.042389  0.500005  0.561147  0.303200
4  0.991908  0.331656  0.591858  0.856721  0.367924

In [46]:
newdf.columns = list("ABCDE")

In [47]:
newdf

            A         B         C         D         E
0    0.200000  0.654081  0.608428  0.631050  0.094173
1    0.086955  0.957513  0.235887  0.648301  0.513132
2    0.680814  0.912251  0.466365  0.297539  0.369094
3    0.859121  0.042389  0.500005  0.561147  0.303200
4    0.991908  0.331656  0.591858  0.856721  0.367924
..        ...       ...       ...       ...       ...
329  0.794219  0.487633  0.035823  0.773380  0.462670
330  0.934680  0.332451  0.875441  0.258823  0.068125
331  0.148264  0.855316  0.596798  0.417520  0.621319
332  0.895031  0.119942  0.625321  0.005616  0.839709
333  0.949934  0.051184  0.692991  0.324124  0.236691

[334 rows x 5 columns]

In [48]:
newdf.loc[0,0] = 74382

In [49]:
newdf

            A         B         C         D         E        0
0    0.200000  0.654081  0.608428  0.631050  0.094173  74382.0
1    0.086955  0.957513  0.235887  0.648301  0.513132      NaN
2    0.680814  0.912251  0.466365  0.297539  0.369094      NaN
3    0.859121  0.042389  0.500005  0.561147  0.303200      NaN
4    0.991908  0.331656  0.591858  0.856721  0.367924      NaN
..        ...       ...       ...       ...       ...      ...
329  0.794219  0.487633  0.035823  0.773380  0.462670      NaN
330  0.934680  0.332451  0.875441  0.258823  0.068125      NaN
331  0.148264  0.855316  0.596798  0.417520  0.621319      NaN
332  0.895031  0.119942  0.625321  0.005616  0.839709      NaN
333  0.949934  0.051184  0.692991  0.324124  0.236691      NaN

[334 rows x 6 columns]

In [56]:
newdf = newdf.drop(0, axis=1)

In [52]:
newdf.loc[[1,2],["C","D"]]

          C         D
1  0.235887  0.648301
2  0.466365  0.297539

In [53]:
newdf.loc[:,["C","D"]]

            C         D
0    0.608428  0.631050
1    0.235887  0.648301
2    0.466365  0.297539
3    0.500005  0.561147
4    0.591858  0.856721
..        ...       ...
329  0.035823  0.773380
330  0.875441  0.258823
331  0.596798  0.417520
332  0.625321  0.005616
333  0.692991  0.324124

[334 rows x 2 columns]

In [58]:
newdf.loc[[1,2],:]

          A         B         C         D         E
1  0.086955  0.957513  0.235887  0.648301  0.513132
2  0.680814  0.912251  0.466365  0.297539  0.369094

In [57]:
newdf.head()

          A         B         C         D         E
0  0.200000  0.654081  0.608428  0.631050  0.094173
1  0.086955  0.957513  0.235887  0.648301  0.513132
2  0.680814  0.912251  0.466365  0.297539  0.369094
3  0.859121  0.042389  0.500005  0.561147  0.303200
4  0.991908  0.331656  0.591858  0.856721  0.367924

In [63]:
newdf.loc[(newdf["A"]<0.3) & (newdf["C"]>0.8)]

            A         B         C         D         E
27   0.073517  0.438893  0.929455  0.672867  0.972219
52   0.224990  0.986472  0.801690  0.137364  0.315412
54   0.270251  0.640346  0.978131  0.723031  0.166002
61   0.254355  0.003307  0.958136  0.944327  0.303555
77   0.059595  0.016926  0.943896  0.684052  0.730955
84   0.282722  0.301258  0.894034  0.251672  0.917939
90   0.024914  0.910243  0.835264  0.385949  0.827915
98   0.045838  0.146893  0.862331  0.794438  0.194408
105  0.128122  0.824549  0.952122  0.285830  0.817687
126  0.087616  0.606731  0.977430  0.956244  0.920486
148  0.245612  0.619527  0.961883  0.932353  0.968026
167  0.237017  0.613954  0.825216  0.667641  0.780381
168  0.243999  0.743945  0.898234  0.144477  0.230836
170  0.197985  0.117655  0.979170  0.948904  0.456776
179  0.002179  0.513488  0.959019  0.614024  0.521598
184  0.188231  0.164706  0.813645  0.249743  0.237029
188  0.043635  0.581009  0.856789  0.081746  0.839739
197  0.202093  0.331610  0.942008  0.667191  0.778211
212  0.111072  0.924226  0.923185  0.495469  0.310888
250  0.199878  0.227526  0.848059  0.388580  0.676085
251  0.072222  0.197916  0.854886  0.446428  0.981999
261  0.008837  0.974525  0.929186  0.251875  0.885421
275  0.074154  0.692035  0.968994  0.007800  0.031299
281  0.042972  0.865537  0.943792  0.676924  0.345014
312  0.269124  0.180602  0.887221  0.843533  0.933429

In [66]:
newdf.head()

          A         B         C         D         E
0  0.200000  0.654081  0.608428  0.631050  0.094173
1  0.086955  0.957513  0.235887  0.648301  0.513132
2  0.680814  0.912251  0.466365  0.297539  0.369094
3  0.859121  0.042389  0.500005  0.561147  0.303200
4  0.991908  0.331656  0.591858  0.856721  0.367924

In [65]:
newdf.iloc[0,4]

0.09417283217244476

In [67]:
newdf.iloc[[1,2],[2,3]]

          C         D
1  0.235887  0.648301
2  0.466365  0.297539

In [68]:
newdf.drop([1,5], axis=0, inplace=True)

In [69]:
newdf

            A         B         C         D         E
0    0.200000  0.654081  0.608428  0.631050  0.094173
2    0.680814  0.912251  0.466365  0.297539  0.369094
3    0.859121  0.042389  0.500005  0.561147  0.303200
4    0.991908  0.331656  0.591858  0.856721  0.367924
6    0.941428  0.092945  0.754851  0.698789  0.662259
..        ...       ...       ...       ...       ...
329  0.794219  0.487633  0.035823  0.773380  0.462670
330  0.934680  0.332451  0.875441  0.258823  0.068125
331  0.148264  0.855316  0.596798  0.417520  0.621319
332  0.895031  0.119942  0.625321  0.005616  0.839709
333  0.949934  0.051184  0.692991  0.324124  0.236691

[332 rows x 5 columns]

In [72]:
newdf.reset_index(drop=True, inplace=True)

In [73]:
newdf

            A         B         C         D         E
0    0.200000  0.654081  0.608428  0.631050  0.094173
1    0.680814  0.912251  0.466365  0.297539  0.369094
2    0.859121  0.042389  0.500005  0.561147  0.303200
3    0.991908  0.331656  0.591858  0.856721  0.367924
4    0.941428  0.092945  0.754851  0.698789  0.662259
..        ...       ...       ...       ...       ...
327  0.794219  0.487633  0.035823  0.773380  0.462670
328  0.934680  0.332451  0.875441  0.258823  0.068125
329  0.148264  0.855316  0.596798  0.417520  0.621319
330  0.895031  0.119942  0.625321  0.005616  0.839709
331  0.949934  0.051184  0.692991  0.324124  0.236691

[332 rows x 5 columns]

In [74]:
newdf.shape

(332, 5)

In [76]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 332 entries, 0 to 331
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       332 non-null    float64
 1   B       332 non-null    float64
 2   C       332 non-null    float64
 3   D       332 non-null    float64
 4   E       332 non-null    float64
dtypes: float64(5)
memory usage: 13.1 KB

In [79]:
pd.read_excel('sample.xlsx',sheet_name='Sheet2')

   Train No1      City  Speed
0     423424     delhi     92
1     343434  gurugram    138
2     343234   chennai    128
3     434565    mumbai     80