In [1]:
import pandas as pd
import numpy as np

1. Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [2]:
data = pd.Series([1,2,3,4,5])

In [3]:
data

0    1
1    2
2    3
3    4
4    5
dtype: int64

2. Write a Python program to convert a Panda module Series to Python list and it's type.

In [4]:
data = data.to_list()

In [5]:
data

[1, 2, 3, 4, 5]

In [6]:
type(data)

list

3. Write a Python program to add, subtract, multiple and divide two Pandas Series.

In [13]:
data1 = pd.Series([2, 4, 6, 8, 10])
data2 = pd.Series([1, 3, 5, 7, 9])

In [14]:
data1.add(data2)

0     3
1     7
2    11
3    15
4    19
dtype: int64

In [15]:
data1.subtract(data2)

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [16]:
data1.multiply(data2)

0     2
1    12
2    30
3    56
4    90
dtype: int64

In [17]:
data1.divide(data2)

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

4. Write a Python program to get the powers of an array values element-wise.

In [18]:
numbers = pd.Series([0,1,2,3,4,5,6])
power = pd.Series([3,3,3,3,3,3])

In [27]:
pow = numbers.rpow(power)

In [28]:
pow

0      1.0
1      3.0
2      9.0
3     27.0
4     81.0
5    243.0
6      NaN
dtype: float64

5. Write a Python program to create and display a DataFrame from a specified dictionary data which has the index labels.

In [89]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [90]:
data = pd.DataFrame(exam_data, index=labels)

In [35]:
data

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

6. Write a Python program to display a summary of the basic information about a specified Data Frame and its data.

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     object
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64
 3   qualify   10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

7. Write a Python program to get the first 3 rows of a given DataFrame

In [37]:
data.head(3)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

8. Write a Python program to select the 'name' and 'score' columns from the following DataFrame.

In [38]:
data.loc[:,["name","score"]]

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

9. Write a Python program to select the specified columns and rows from a given data frame.
Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.

In [41]:
data.loc[["a","c","e","f"],["name","score"]]

        name  score
a  Anastasia   12.5
c  Katherine   16.5
e      Emily    9.0
f    Michael   20.0

10. Write a Python program to select the rows where the number of attempts in the examination is greater than 2.

In [42]:
data.loc[data["attempts"] > 2]

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

11. Write a Python program to count the number of rows and columns of a DataFrame.

In [44]:
data.shape

(10, 4)

12. Write a Python program to select the rows where the score is missing, i.e. is NaN.

In [48]:
data.loc[data["score"].isna()]

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

13. Write a Python program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.

In [49]:
data.loc[(data["attempts"] < 2) & (data["score"] > 15)]

    name  score  attempts qualify
j  Jonas   19.0         1     yes

14. Write a Python program to change the score in row 'd' to 11.5.

In [50]:
data.loc[["d"],["score"]] = 11.5

In [51]:
data

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

15. Write a Python program to calculate the sum of the examination attempts by the students.

In [52]:
data["attempts"].sum()

19

16. Write a Python program to calculate the mean score for each different student in DataFrame.

In [58]:
data.groupby("name")["score"].mean()

name
Anastasia    12.5
Dima          9.0
Emily         9.0
James        11.5
Jonas        19.0
Katherine    16.5
Kevin         8.0
Laura         NaN
Matthew      14.5
Michael      20.0
Name: score, dtype: float64

17. Write a Python program to append a new row 'k' to data frame with given values for each column. Now delete the new row and return the original DataFrame.

In [73]:
new_data = pd.DataFrame({'name' : "Suresh", 'score': 15.5, 'attempts': 1, 'qualify': "yes"},index=["k"])

In [75]:
data = pd.concat([data,new_data])

In [77]:
data

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes

In [79]:
data.drop(["k"], inplace=True)

In [91]:
data

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

18. Write a Python program to sort the DataFrame first by 'name' in descending order, then by 'score' in ascending order.

In [83]:
data.sort_values(by="name", ascending=False)

        name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes

In [84]:
data.sort_values(by="score")

        name  score  attempts qualify
i      Kevin    8.0         2      no
b       Dima    9.0         3      no
e      Emily    9.0         2      no
d      James   11.5         3      no
a  Anastasia   12.5         1     yes
g    Matthew   14.5         1     yes
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
f    Michael   20.0         3     yes
h      Laura    NaN         1      no

19. Write a Python program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.

In [93]:
data["qualify"] = data["qualify"].replace({"yes" : True, "no" : False})

C:\Users\saram\AppData\Local\Temp\ipykernel_17760\2776295814.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["qualify"] = data["qualify"].replace({"yes" : True, "no" : False})

In [94]:
data

        name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James    NaN         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True

20. Write a Python program to delete the 'attempts' column from the DataFrame.

In [99]:
data.drop(["attempts"],axis=1, inplace=True)

21. Write a Python program to insert a new column in existing DataFrame.

In [100]:
data = data.assign(attempts = [1, 3, 2, 3, 2, 3, 1, 1, 2, 1])

In [101]:
data

        name  score  qualify  attempts
a  Anastasia   12.5     True         1
b       Dima    9.0    False         3
c  Katherine   16.5     True         2
d      James    NaN    False         3
e      Emily    9.0    False         2
f    Michael   20.0     True         3
g    Matthew   14.5     True         1
h      Laura    NaN    False         1
i      Kevin    8.0    False         2
j      Jonas   19.0     True         1

22. Write a Python program to iterate over rows in a DataFrame.

In [106]:
for index, items in data.iterrows():
    print(index)
    print(items)

a
name        Anastasia
score            12.5
qualify          True
attempts            1
Name: a, dtype: object
b
name         Dima
score         9.0
qualify     False
attempts        3
Name: b, dtype: object
c
name        Katherine
score            16.5
qualify          True
attempts            2
Name: c, dtype: object
d
name        James
score         NaN
qualify     False
attempts        3
Name: d, dtype: object
e
name        Emily
score         9.0
qualify     False
attempts        2
Name: e, dtype: object
f
name        Michael
score          20.0
qualify        True
attempts          3
Name: f, dtype: object
g
name        Matthew
score          14.5
qualify        True
attempts          1
Name: g, dtype: object
h
name        Laura
score         NaN
qualify     False
attempts        1
Name: h, dtype: object
i
name        Kevin
score         8.0
qualify     False
attempts        2
Name: i, dtype: object
j
name        Jonas
score        19.0
qualify      True
attempts        1
Name: j, dtype: object

23. Write a Python program to get list from DataFrame column headers.

In [111]:
col_list = data.columns.to_list()

In [112]:
col_list

['name', 'score', 'qualify', 'attempts']